# Build patient's utility matrix

In [20]:
import json
sys.path.append('../')
from utilities import from_dict_to_df
import pandas as pd

In [21]:
# open dataset
with open('../../data/full_data.json', 'r') as file:
    data = json.load(file)

In [22]:
conditions_df = pd.DataFrame(data['Conditions'])
therapies_df = pd.DataFrame(data['Therapies'])
patients_df = pd.DataFrame(data['Patients'])

## Initialize the emply df

In [23]:
prova = pd.DataFrame(columns = list(therapies_df['id'].values), index= list(conditions_df['id'].values))
#prova = prova.fillna(0)
prova

ther_0 ther_1 ther_2 ther_3 ther_4 ther_5 ther_6 ther_7 ther_8  \
cond_0      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_1      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_2      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_3      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_4      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
cond_304    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_305    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_306    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_307    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_308    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

         ther_9  ... ther_57 ther_58 ther_59 ther_60 ther_61 ther_62 ther_63  \
cond_0      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_1      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_2      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_3      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_4      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...  ...     ...     ...     ...     ...     ...     ...     ...   
cond_304    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_305    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_306    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_307    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_308    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

         ther_64 ther_65 ther_66  
cond_0       NaN     NaN     NaN  
cond_1       NaN     NaN     NaN  
cond_2       NaN     NaN     NaN  
cond_3       NaN     NaN     NaN  
cond_4       NaN     NaN     NaN  
...          ...     ...     ...  
cond_304     NaN     NaN     NaN  
cond_305     NaN     NaN     NaN  
cond_306     NaN     NaN     NaN  
cond_307     NaN     NaN     NaN  
cond_308     NaN     NaN     NaN  

[309 rows x 67 columns]

### eg with one patient

In [24]:
p_1 = patients_df[patients_df.id == 'pat_0']

# trials for each cond df
trials = pd.DataFrame(p_1.trials.values[0])
cond = pd.DataFrame(p_1.conditions.values[0])

add true cond_id to the trial df:

In [25]:
trials['cond_id'] = ""

for idx,row in trials.iterrows():
    pat_cond = row['condition']
    cond_id = cond[cond.id == pat_cond].kind.values[0]
    trials.loc[idx,'cond_id'] = cond_id

fill the utility matrix for the patient

In [26]:
for idx,row in trials.iterrows():
    matrix_pat_1 = prova
    
    cond = row['cond_id']
    ther = row['therapy']
    succ = row['successful']
    matrix_pat_1.loc[cond,ther] = succ
# normalize
norm_matrix = matrix_pat_1.sub(matrix_pat_1.mean(axis=1), axis=0)
norm_matrix

ther_0 ther_1 ther_2 ther_3 ther_4 ther_5 ther_6 ther_7 ther_8  \
cond_0      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_1      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_2      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_3      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_4      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
cond_304    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_305    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_306    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_307    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
cond_308    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

         ther_9  ... ther_57 ther_58 ther_59 ther_60 ther_61 ther_62 ther_63  \
cond_0      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_1      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_2      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_3      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_4      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...  ...     ...     ...     ...     ...     ...     ...     ...   
cond_304    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_305    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_306    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_307    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
cond_308    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

         ther_64 ther_65 ther_66  
cond_0       NaN     NaN     NaN  
cond_1       NaN     NaN     NaN  
cond_2       NaN     NaN     NaN  
cond_3       NaN     NaN     NaN  
cond_4       NaN     NaN     NaN  
...          ...     ...     ...  
cond_304     NaN     NaN     NaN  
cond_305     NaN     NaN     NaN  
cond_306     NaN     NaN     NaN  
cond_307     NaN     NaN     NaN  
cond_308     NaN     NaN     NaN  

[309 rows x 67 columns]

Fill with 0 where we have Nan

In [27]:
final_matrix = norm_matrix.fillna(0)
# check
final_matrix[final_matrix.index=='cond_158']

ther_0    ther_1     ther_2  ther_3  ther_4     ther_5  ther_6  \
cond_158     0.0  8.545455  29.545455     0.0       0  17.545455     0.0   

          ther_7     ther_8  ther_9  ...  ther_57  ther_58    ther_59  \
cond_158       0 -25.454545     0.0  ...      0.0      0.0  20.545455   

          ther_60  ther_61  ther_62  ther_63  ther_64  ther_65  ther_66  
cond_158        0      0.0      0.0      0.0      0.0      0.0      0.0  

[1 rows x 67 columns]

----
# Function

In [17]:
def utility_matrix(patient_id):
    # # open dataset
    # with open('../../data/full_data.json', 'r') as file:
    #     data = json.load(file)
    
    conditions_df = pd.DataFrame(data['Conditions'])
    therapies_df = pd.DataFrame(data['Therapies'])
    patients_df = pd.DataFrame(data['Patients'])
    
    # initialize empty utility matrix
    prova = pd.DataFrame(columns = list(therapies_df['id'].values), index= list(conditions_df['id'].values))
    
    # extract data for the patient
    pat = patients_df[patients_df.id == patient_id]

    # trials and cond
    trials = pd.DataFrame(pat.trials.values[0])
    cond = pd.DataFrame(pat.conditions.values[0])
    
    # add true cond_id to trial data
    trials['cond_id'] = ""

    for idx,row in trials.iterrows():
        pat_cond = row['condition']
        cond_id = cond[cond.id == pat_cond].kind.values[0]
        trials.loc[idx,'cond_id'] = cond_id
        
    # fill utility matrix
    for idx,row in trials.iterrows():
        matrix_pat = prova
        
        cond = row['cond_id']
        ther = row['therapy']
        succ = row['successful']
        matrix_pat.loc[cond,ther] = succ
    # normalize
    norm_matrix = matrix_pat.sub(matrix_pat.mean(axis=1), axis=0)
    final_matrix = norm_matrix.fillna(0)
    return final_matrix
    

## Compute cosine similarity between the two patients matrices

In [64]:
pat_0 = utility_matrix("pat_0")
pat_1 = utility_matrix("pat_1")

mat_0 = pat_0.to_numpy()
mat_1 = pat_1.to_numpy()

import numpy as np
import scipy.spatial.distance as distance
c = 1 - distance.cosine(mat_0.flatten(), mat_1.flatten())
c

0.00894254170352704

In [66]:
mat_0.flatten()[:1000]

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [51]:
from scipy.spatial import distance
u = np.arange(6).reshape(3,2)
v = [0, 1, 0]

u

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
v

[0, 1, 0]

In [48]:
u = np.arange(3)
v = v = [0, 1, 0]

u

array([0, 1, 2])